"""Initial migration

Revision ID: 286f9f662869
Revises: 
Create Date: 2026-06-10 21:33:30.391166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286f9f662869'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('alcohol_content', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('winery', sa.String(length=200), nullable=False),
    sa.Column('winery_url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_crawled', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('wines', schema=None) as batch_op:
        batch_op.create_index('idx_wine_alcohol', ['alcohol_content'], unique=False)
        batch_op.create_index('idx_wine_winery', ['winery'], unique=False)
        batch_op.create_index(batch_op.f('ix_wines_winery'), ['winery'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wines_winery'))
        batch_op.drop_index('idx_wine_winery')
        batch_op.drop_index('idx_wine_alcohol')

    op.drop_table('wines')
    # ### end Alembic commands ###
